<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class DentalRecordsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Get all user IDs (patients)
        $userIds = DB::table('users')->where('usertype', 'user')->pluck('id')->toArray();
        
        // Get dentist IDs
        $dentistIds = DB::table('users')->where('usertype', 'admin')->pluck('id')->toArray();

        if (empty($userIds) || empty($dentistIds)) {
            $this->command->warn('No users or dentists found. Please run UserSeeder first.');
            return;
        }

        $dentalRecords = [
            // Records for first few patients
            [
                'user_id' => $userIds[0] ?? null,
                'dentist_id' => $dentistIds[0] ?? null,
                'visit_date' => Carbon::now()->subMonths(3)->format('Y-m-d'),
                'chief_complaint' => 'Toothache on upper right molar',
                'medical_history' => 'No significant medical history.',
                'current_medications' => 'None',
                'allergies' => 'No known allergies',
                'blood_pressure' => '120/80',
                'oral_examination' => 'Good overall oral health, isolated cavity detected',
                'gum_condition' => 'Healthy gums, no inflammation',
                'tooth_condition' => 'Deep cavity on tooth #14',
                'xray_findings' => 'Deep carious lesion extending to pulp',
                'diagnosis' => 'Deep cavity on tooth #14 with pulp involvement',
                'treatment_plan' => 'Root canal treatment followed by crown placement',
                'treatment_performed' => 'Root canal treatment and temporary filling',
                'teeth_numbers' => '14',
                'prescription' => 'Amoxicillin 500mg TID for 7 days, Mefenamic Acid 500mg TID as needed',
                'recommendations' => 'Avoid hard foods, maintain good oral hygiene',
                'next_visit' => Carbon::now()->subMonths(2)->format('Y-m-d'),
                'notes' => 'Patient advised to avoid hard foods. Follow-up for permanent crown.',
            ],
            [
                'user_id' => $userIds[0] ?? null,
                'dentist_id' => $dentistIds[0] ?? null,
                'visit_date' => Carbon::now()->subMonths(2)->format('Y-m-d'),
                'chief_complaint' => 'Follow-up for permanent crown',
                'medical_history' => 'No significant medical history',
                'current_medications' => 'None',
                'allergies' => 'No known allergies',
                'blood_pressure' => '118/78',
                'oral_examination' => 'Healing well post root canal',
                'gum_condition' => 'Healthy',
                'tooth_condition' => 'Tooth #14 ready for crown',
                'xray_findings' => 'Root canal treatment successful',
                'diagnosis' => 'Post root canal - ready for crown',
                'treatment_plan' => 'Permanent crown placement',
                'treatment_performed' => 'Permanent crown installation on tooth #14',
                'teeth_numbers' => '14',
                'prescription' => 'None',
                'recommendations' => 'Regular dental check-ups every 6 months',
                'next_visit' => Carbon::now()->addMonths(6)->format('Y-m-d'),
                'notes' => 'Crown fitted perfectly. Regular check-up in 6 months.',
            ],
            [
                'user_id' => $userIds[1] ?? null,
                'dentist_id' => $dentistIds[1] ?? null,
                'visit_date' => Carbon::now()->subMonths(1)->format('Y-m-d'),
                'chief_complaint' => 'Bleeding gums and bad breath',
                'medical_history' => 'Hypertension, controlled with medication',
                'current_medications' => 'Amlodipine 5mg once daily',
                'allergies' => 'None',
                'blood_pressure' => '135/85',
                'oral_examination' => 'Generalized gingival inflammation',
                'gum_condition' => 'Gingivitis with moderate tartar buildup',
                'tooth_condition' => 'Multiple teeth with plaque and calculus',
                'xray_findings' => 'No bone loss detected',
                'diagnosis' => 'Gingivitis with moderate tartar buildup',
                'treatment_plan' => 'Scaling and polishing, oral hygiene instructions',
                'treatment_performed' => 'Complete scaling and polishing',
                'teeth_numbers' => 'All teeth',
                'prescription' => 'Chlorhexidine mouthwash 0.2% BID for 2 weeks',
                'recommendations' => 'Proper brushing technique, daily flossing, regular dental visits',
                'next_visit' => Carbon::now()->addMonths(3)->format('Y-m-d'),
                'notes' => 'Patient advised proper brushing and flossing techniques.',
            ],
            [
                'user_id' => $userIds[2] ?? null,
                'dentist_id' => $dentistIds[0] ?? null,
                'visit_date' => Carbon::now()->subWeeks(3)->format('Y-m-d'),
                'chief_complaint' => 'Wisdom tooth pain',
                'medical_history' => 'No known medical conditions',
                'current_medications' => 'None',
                'allergies' => 'No known allergies',
                'blood_pressure' => '115/75',
                'oral_examination' => 'Impacted lower right wisdom tooth',
                'gum_condition' => 'Inflamed tissue around wisdom tooth',
                'tooth_condition' => 'Impacted tooth #48',
                'xray_findings' => 'Horizontally impacted wisdom tooth',
                'diagnosis' => 'Impacted lower right wisdom tooth',
                'treatment_plan' => 'Surgical extraction',
                'treatment_performed' => 'Surgical extraction of tooth #48',
                'teeth_numbers' => '48',
                'prescription' => 'Amoxicillin 500mg TID for 5 days, Ibuprofen 400mg TID for pain',
                'recommendations' => 'Ice pack for 24 hours, soft diet, avoid strenuous activities',
                'next_visit' => Carbon::now()->addWeeks(1)->format('Y-m-d'),
                'notes' => 'Post-operative instructions given. Sutures to be removed in 1 week.',
            ],
            [
                'user_id' => $userIds[3] ?? null,
                'dentist_id' => $dentistIds[1] ?? null,
                'visit_date' => Carbon::now()->subWeeks(2)->format('Y-m-d'),
                'chief_complaint' => 'Teeth discoloration and staining',
                'medical_history' => 'No significant medical history',
                'current_medications' => 'None',
                'allergies' => 'None',
                'blood_pressure' => '122/80',
                'oral_examination' => 'Good oral health with extrinsic staining',
                'gum_condition' => 'Healthy gums',
                'tooth_condition' => 'Extrinsic staining on multiple teeth',
                'xray_findings' => 'No caries detected',
                'diagnosis' => 'Extrinsic tooth staining',
                'treatment_plan' => 'Professional teeth whitening',
                'treatment_performed' => 'In-office teeth whitening treatment',
                'teeth_numbers' => 'All anterior teeth',
                'prescription' => 'Fluoride toothpaste for sensitive teeth',
                'recommendations' => 'Reduce coffee and smoking, maintain good oral hygiene',
                'next_visit' => Carbon::now()->addMonths(6)->format('Y-m-d'),
                'notes' => 'Patient satisfied with results. Regular check-up in 6 months.',
            ],
            [
                'user_id' => $userIds[4] ?? null,
                'dentist_id' => $dentistIds[0] ?? null,
                'visit_date' => Carbon::now()->subDays(10)->format('Y-m-d'),
                'chief_complaint' => 'Broken front tooth',
                'medical_history' => 'Asthma, uses inhaler',
                'current_medications' => 'Salbutamol inhaler as needed',
                'allergies' => 'No known allergies',
                'blood_pressure' => '118/76',
                'oral_examination' => 'Fractured central incisor',
                'gum_condition' => 'Healthy',
                'tooth_condition' => 'Fractured tooth #11',
                'xray_findings' => 'No root damage detected',
                'diagnosis' => 'Fractured central incisor #11',
                'treatment_plan' => 'Composite restoration',
                'treatment_performed' => 'Composite restoration and bonding',
                'teeth_numbers' => '11',
                'prescription' => 'None',
                'recommendations' => 'Avoid biting hard objects',
                'next_visit' => Carbon::now()->addMonths(3)->format('Y-m-d'),
                'notes' => 'Tooth restored to original shape. Patient satisfied.',
            ],
            [
                'user_id' => $userIds[5] ?? null,
                'dentist_id' => $dentistIds[1] ?? null,
                'visit_date' => Carbon::now()->subDays(5)->format('Y-m-d'),
                'chief_complaint' => 'Routine check-up',
                'medical_history' => 'Diabetes Type 2, controlled',
                'current_medications' => 'Metformin 500mg BID',
                'allergies' => 'None',
                'blood_pressure' => '128/82',
                'oral_examination' => 'Excellent oral hygiene',
                'gum_condition' => 'Healthy gums',
                'tooth_condition' => 'Minor plaque buildup',
                'xray_findings' => 'No abnormalities detected',
                'diagnosis' => 'Healthy teeth and gums',
                'treatment_plan' => 'Prophylaxis and fluoride treatment',
                'treatment_performed' => 'Professional cleaning and fluoride application',
                'teeth_numbers' => 'All teeth',
                'prescription' => 'None',
                'recommendations' => 'Continue excellent oral hygiene, regular visits',
                'next_visit' => Carbon::now()->addMonths(6)->format('Y-m-d'),
                'notes' => 'Excellent oral hygiene. Continue regular visits.',
            ],
            [
                'user_id' => $userIds[6] ?? null,
                'dentist_id' => $dentistIds[0] ?? null,
                'visit_date' => Carbon::now()->subDays(3)->format('Y-m-d'),
                'chief_complaint' => 'Sensitivity to cold',
                'medical_history' => 'No known medical conditions',
                'current_medications' => 'None',
                'allergies' => 'None',
                'blood_pressure' => '120/78',
                'oral_examination' => 'Exposed dentin on multiple teeth',
                'gum_condition' => 'Mild gingival recession',
                'tooth_condition' => 'Dentinal hypersensitivity',
                'xray_findings' => 'No caries detected',
                'diagnosis' => 'Dentinal hypersensitivity',
                'treatment_plan' => 'Fluoride varnish and desensitizing treatment',
                'treatment_performed' => 'Fluoride varnish application',
                'teeth_numbers' => '13,23,33,43',
                'prescription' => 'Sensodyne toothpaste for daily use',
                'recommendations' => 'Use soft-bristled toothbrush, avoid acidic foods',
                'next_visit' => Carbon::now()->addMonths(1)->format('Y-m-d'),
                'notes' => 'Sensitivity should reduce in 1-2 weeks.',
            ],
            [
                'user_id' => $userIds[7] ?? null,
                'dentist_id' => $dentistIds[1] ?? null,
                'visit_date' => Carbon::now()->yesterday()->format('Y-m-d'),
                'chief_complaint' => 'Lost filling',
                'medical_history' => 'No significant medical history',
                'current_medications' => 'None',
                'allergies' => 'None',
                'blood_pressure' => '119/77',
                'oral_examination' => 'Lost amalgam filling on upper left molar',
                'gum_condition' => 'Healthy',
                'tooth_condition' => 'Cavity without filling on tooth #26',
                'xray_findings' => 'Medium-depth cavity',
                'diagnosis' => 'Lost amalgam filling on tooth #26',
                'treatment_plan' => 'Composite filling replacement',
                'treatment_performed' => 'New composite filling placement',
                'teeth_numbers' => '26',
                'prescription' => 'None',
                'recommendations' => 'Avoid hard foods for 24 hours',
                'next_visit' => Carbon::now()->addMonths(6)->format('Y-m-d'),
                'notes' => 'Patient advised to avoid chewing hard foods for 24 hours.',
            ],
        ];

        foreach ($dentalRecords as $record) {
            if ($record['user_id'] && $record['dentist_id']) {
                DB::table('dental_records')->insert([
                    'user_id' => $record['user_id'],
                    'dentist_id' => $record['dentist_id'],
                    'visit_date' => $record['visit_date'],
                    'chief_complaint' => $record['chief_complaint'],
                    'medical_history' => $record['medical_history'],
                    'current_medications' => $record['current_medications'],
                    'allergies' => $record['allergies'],
                    'blood_pressure' => $record['blood_pressure'],
                    'oral_examination' => $record['oral_examination'],
                    'gum_condition' => $record['gum_condition'],
                    'tooth_condition' => $record['tooth_condition'],
                    'xray_findings' => $record['xray_findings'],
                    'diagnosis' => $record['diagnosis'],
                    'treatment_plan' => $record['treatment_plan'],
                    'treatment_performed' => $record['treatment_performed'],
                    'teeth_numbers' => $record['teeth_numbers'],
                    'prescription' => $record['prescription'],
                    'recommendations' => $record['recommendations'],
                    'next_visit' => $record['next_visit'],
                    'notes' => $record['notes'],
                    'created_at' => now(),
                    'updated_at' => now(),
                ]);
            }
        }
    }
}
